apiVersion: v1
kind: Service
metadata:
  name: uv-fastapi-example
spec:
  selector:
    app: uv-fastapi-example
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uv-fastapi-example
spec:
  selector:
    matchLabels:
      app: uv-fastapi-example
  replicas: 4
  template:
    metadata:
      labels:
        app: uv-fastapi-example
    spec:
      containers:
        - name: uv-fastapi-example
          image: uv-fastapi-example:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
